In [ ]:
!pip install numpy

In [106]:
import numpy as np

In [ ]:
a = np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
print(a[11])

11


In [ ]:
print(a[-1])

11


In [ ]:
print(a[10:])

print(a[-2:])

[10 11]
[10 11]


In [ ]:
print(a)
print(a[-4:])
print(np.sum(a[-4:]))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 8  9 10 11]
38


In [ ]:
print(5*1)
print(5*True)
print(5*False)

5
5
0


In [ ]:
a = np.array([0,1,2,3,4,5])
# b = np.array([0,0,0,1,1,1])
b = np.array([False,False,False,True,True,True])
print(a*b)

[0 0 0 3 4 5]


In [ ]:
a = np.arange(12)

mask = a%2==0
print(a)
print(mask)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ True False  True False  True False  True False  True False  True False]


In [ ]:
a = np.arange(25).reshape(5,5)
mask = np.array([[1,1,1,1,1],
                 [1,0,0,0,1],
                 [1,0,0,0,1],
                 [1,0,0,0,1],
                 [1,1,1,1,1]
                 ])
print(a)
print(mask)
print(a*mask)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
[[ 0  1  2  3  4]
 [ 5  0  0  0  9]
 [10  0  0  0 14]
 [15  0  0  0 19]
 [20 21 22 23 24]]


In [ ]:
a = np.arange(25).reshape(5,5)
mask = np.ones_like(a)
mask[1:-1,1:-1] = 0

print(a)
print(mask)
print(a * mask)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
[[ 0  1  2  3  4]
 [ 5  0  0  0  9]
 [10  0  0  0 14]
 [15  0  0  0 19]
 [20 21 22 23 24]]


In [ ]:
a = np.arange(25).reshape(5,5)
mask = np.eye(5)

print(a)
print(mask)
print(a * mask)
print(np.sum(a*mask))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[ 0.  0.  0.  0.  0.]
 [ 0.  6.  0.  0.  0.]
 [ 0.  0. 12.  0.  0.]
 [ 0.  0.  0. 18.  0.]
 [ 0.  0.  0.  0. 24.]]
60.0


In [ ]:
a = [0,1,2,3,4]
print(a)
a.insert(3,99)
print(a)

[0, 1, 2, 3, 4]
[0, 1, 2, 99, 3, 4]


In [ ]:
a = np.arange(4)
print(a)
print(a.shape)
a = a.reshape((4,1))
print(a)

a = a.reshape((1,4))
print(a)

a = a.reshape((2,2))
print(a)

[0 1 2 3]
(4,)
[[0]
 [1]
 [2]
 [3]]
[[0 1 2 3]]
[[0 1]
 [2 3]]


In [ ]:
a = np.arange(12)
a = np.expand_dims(a, axis=-1)
print(a)

a = np.arange(12)
a = np.expand_dims(a, axis=0)
print(a)

a = np.arange(12)
a = np.expand_dims(a, axis=1)
print(a)

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11]]
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]


In [ ]:
a = np.arange(6).reshape((1,2,3))
print(a)
print("-------------")
a = np.arange(6).reshape((2,1,3))
print(a)
print("-------------")
a = np.arange(6).reshape((2,3,1))
print(a)

[[[0 1 2]
  [3 4 5]]]
-------------
[[[0 1 2]]

 [[3 4 5]]]
-------------
[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]]


In [ ]:
a = np.arange(12).reshape((1,3,4))
print(a)
print(a.shape)
print("-------------")
a = np.squeeze(a)
print(a)
print(a.shape)


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]
(1, 3, 4)
-------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [ ]:
a = np.arange(12).reshape((1,3,1,4))
print(a)
print(a.shape)
print("-------------")
a = np.squeeze(a)
print(a)
print(a.shape)

[[[[ 0  1  2  3]]

  [[ 4  5  6  7]]

  [[ 8  9 10 11]]]]
(1, 3, 1, 4)
-------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [ ]:
a = np.arange(12)
a = a.reshape((3,-1))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
a = np.arange(12).reshape(3,4)
print(a)
print(a.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [ ]:
a = np.arange(15).reshape((5,3))
print(a)
print("--------------")
print(np.sum(a, axis=0))
print(np.mean(a, axis=0))
print("--------------")
print(np.sum(a,axis=1))
print(np.mean(a, axis=1))


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
--------------
[30 35 40]
[6. 7. 8.]
--------------
[ 3 12 21 30 39]
[ 1.  4.  7. 10. 13.]


In [ ]:
a = np.arange(60).reshape((3,4,5))
print(a)
# (3,4)
print("--------------")
print(np.sum(a,axis=2))

#(4,5)
print("--------------")
print(np.sum(a,axis=0))

#(3,5)
print("--------------")
print(np.sum(a,axis=1))

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]
--------------
[[ 10  35  60  85]
 [110 135 160 185]
 [210 235 260 285]]
--------------
[[ 60  63  66  69  72]
 [ 75  78  81  84  87]
 [ 90  93  96  99 102]
 [105 108 111 114 117]]
--------------
[[ 30  34  38  42  46]
 [110 114 118 122 126]
 [190 194 198 202 206]]


In [ ]:
a = np.array([[170,65],
              [165,55],
              [171,70],
              [155,50],
              [165,55]
              ])
print(a)
print(a.shape)
print("--------------")
print(np.mean(a,axis=0))

[[170  65]
 [165  55]
 [171  70]
 [155  50]
 [165  55]]
(5, 2)
--------------
[165.2  59. ]


In [ ]:
a = np.array([1,3,5,2,4])
print(np.max(a))
print(np.argmax(a))

5
2


In [ ]:
a = np.array([[170,65],
              [165,75],
              [171,70],
              [155,50],
              [165,55]
              ])
print(a)
print("--------------")
print(np.mean(a,axis=0))
print(np.max(a,axis=0))
print(np.argmax(a,axis=0))

[[170  65]
 [165  75]
 [171  70]
 [155  50]
 [165  55]]
--------------
[165.2  63. ]
[171  75]
[2 1]


In [ ]:
a = np.random.rand(12).reshape(4,3)
print(a)
print(np.max(a,axis=1))
print(np.argmax(a,axis=1))

[[0.9870136  0.05893425 0.58087855]
 [0.44736282 0.15460899 0.18966582]
 [0.37101561 0.0560217  0.17547197]
 [0.97813613 0.06603368 0.01539853]]
[0.9870136  0.44736282 0.37101561 0.97813613]
[0 0 0 0]


In [ ]:
a = np.array([3,7,5,1,8,6,4])
print(np.sort(a))
print(np.argsort(a))

[1 3 4 5 6 7 8]
[3 0 6 2 5 1 4]


In [ ]:
a = np.arange(6).reshape((2,3))
b = np.arange(6,12).reshape((2,3))
print(a)
print(b)
print(np.vstack([a,b]))
print(np.hstack([a,b]))

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]


In [ ]:
a = np.arange(12).reshape((3,4))
np.savetxt("my_data.csv", a, delimiter=",")

In [ ]:
b = np.loadtxt("my_data.csv", delimiter=",")
print(b)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [ ]:
print(b.dtype)

float64


In [ ]:
print(b.astype(np.int))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
a = np.arange(6)
print(a)
print(a.astype(np.float))

[0 1 2 3 4 5]
[0. 1. 2. 3. 4. 5.]


In [110]:
names = np.array(["Tom","Jerry","Brute","철수","영희"])
print(names)
heights = np.array([170,177,165,155,175])
print(heights)
print(np.sort(heights))
print(np.argsort(heights))

# heights_ordered_index = np.array([3,2,0,4,1])
# print(names[heights_ordered_index])
print(names[np.argsort(heights)])

['Tom' 'Jerry' 'Brute' '철수' '영희']
[170 177 165 155 175]
[155 165 170 175 177]
[3 2 0 4 1]
['철수' 'Brute' 'Tom' '영희' 'Jerry']


In [113]:
i = np.array([0,3,4,1,2,0,4,2,2])
print(names[i])

['Tom' '철수' '영희' 'Jerry' 'Brute' 'Tom' '영희' 'Brute' 'Brute']


In [114]:
e = np.eye(5)
print(e)
print(e[i])

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]]
